package org.bpm.model;
// Generated May 13, 2023, 9:40:18 AM by Hibernate Tools 5.4.30.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuestionResponse generated by hbm2java
 */
@Entity
@Table(name="question_response"
    ,schema="public"
)
public class QuestionResponse  implements java.io.Serializable {


     private int id;
     private OpenAiEngines openAiEngines;
     private QuestionCategory questionCategory;
     private Questions questions;
     private String response;
     private Date responseTimestamp;

    public QuestionResponse() {
    }

    public QuestionResponse(int id, OpenAiEngines openAiEngines, QuestionCategory questionCategory, Questions questions, String response, Date responseTimestamp) {
       this.id = id;
       this.openAiEngines = openAiEngines;
       this.questionCategory = questionCategory;
       this.questions = questions;
       this.response = response;
       this.responseTimestamp = responseTimestamp;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="engine_fk", nullable=false)
    public OpenAiEngines getOpenAiEngines() {
        return this.openAiEngines;
    }
    
    public void setOpenAiEngines(OpenAiEngines openAiEngines) {
        this.openAiEngines = openAiEngines;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_fk", nullable=false)
    public QuestionCategory getQuestionCategory() {
        return this.questionCategory;
    }
    
    public void setQuestionCategory(QuestionCategory questionCategory) {
        this.questionCategory = questionCategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="question_fk", nullable=false)
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }

    
    @Column(name="response", nullable=false)
    public String getResponse() {
        return this.response;
    }
    
    public void setResponse(String response) {
        this.response = response;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="response_timestamp", nullable=false, length=35)
    public Date getResponseTimestamp() {
        return this.responseTimestamp;
    }
    
    public void setResponseTimestamp(Date responseTimestamp) {
        this.responseTimestamp = responseTimestamp;
    }




}


