package org.bpm.model;
// Generated May 13, 2023, 9:40:18 AM by Hibernate Tools 5.4.30.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SamplePerson generated by hbm2java
 */
@Entity
@Table(name="sample_person"
    ,schema="public"
)
public class SamplePerson  implements java.io.Serializable {


     private long id;
     private int version;
     private Date dateOfBirth;
     private String email;
     private String firstName;
     private boolean important;
     private String lastName;
     private String occupation;
     private String phone;
     private String role;

    public SamplePerson() {
    }

	
    public SamplePerson(long id, boolean important) {
        this.id = id;
        this.important = important;
    }
    public SamplePerson(long id, Date dateOfBirth, String email, String firstName, boolean important, String lastName, String occupation, String phone, String role) {
       this.id = id;
       this.dateOfBirth = dateOfBirth;
       this.email = email;
       this.firstName = firstName;
       this.important = important;
       this.lastName = lastName;
       this.occupation = occupation;
       this.phone = phone;
       this.role = role;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Version
    @Column(name="version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_of_birth", length=13)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="first_name")
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="important", nullable=false)
    public boolean isImportant() {
        return this.important;
    }
    
    public void setImportant(boolean important) {
        this.important = important;
    }

    
    @Column(name="last_name")
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="occupation")
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    
    @Column(name="phone")
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="role")
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


