package org.bpm.model;
// Generated May 13, 2023, 9:40:18 AM by Hibernate Tools 5.4.30.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * OpenAiEngines generated by hbm2java
 */
@Entity
@Table(name="open_ai_engines"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"id_name", "owner"}) 
)
public class OpenAiEngines  implements java.io.Serializable {


     private int id;
     private String idName;
     private boolean ready;
     private String owner;
     private String permissions;
     private Date created;
     private String description;
     private Set<QuestionResponse> questionResponses = new HashSet<QuestionResponse>(0);

    public OpenAiEngines() {
    }

	
    public OpenAiEngines(int id, String idName, boolean ready) {
        this.id = id;
        this.idName = idName;
        this.ready = ready;
    }
    public OpenAiEngines(int id, String idName, boolean ready, String owner, String permissions, Date created, String description, Set<QuestionResponse> questionResponses) {
       this.id = id;
       this.idName = idName;
       this.ready = ready;
       this.owner = owner;
       this.permissions = permissions;
       this.created = created;
       this.description = description;
       this.questionResponses = questionResponses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="id_name", nullable=false)
    public String getIdName() {
        return this.idName;
    }
    
    public void setIdName(String idName) {
        this.idName = idName;
    }

    
    @Column(name="ready", nullable=false)
    public boolean isReady() {
        return this.ready;
    }
    
    public void setReady(boolean ready) {
        this.ready = ready;
    }

    
    @Column(name="owner")
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }

    
    @Column(name="permissions")
    public String getPermissions() {
        return this.permissions;
    }
    
    public void setPermissions(String permissions) {
        this.permissions = permissions;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", length=35)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="openAiEngines")
    public Set<QuestionResponse> getQuestionResponses() {
        return this.questionResponses;
    }
    
    public void setQuestionResponses(Set<QuestionResponse> questionResponses) {
        this.questionResponses = questionResponses;
    }




}


