package org.bpm.model;
// Generated May 13, 2023, 9:40:18 AM by Hibernate Tools 5.4.30.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Questions generated by hbm2java
 */
@Entity
@Table(name="questions"
    ,schema="public"
)
public class Questions  implements java.io.Serializable {


     private int id;
     private QuestionCategory questionCategory;
     private String question;
     private int step;
     private Integer parentQuestionId;
     private Date createdTimestamp;
     private Set<QuestionResponse> questionResponses = new HashSet<QuestionResponse>(0);

    public Questions() {
    }

	
    public Questions(int id, QuestionCategory questionCategory, String question, int step, Date createdTimestamp) {
        this.id = id;
        this.questionCategory = questionCategory;
        this.question = question;
        this.step = step;
        this.createdTimestamp = createdTimestamp;
    }
    public Questions(int id, QuestionCategory questionCategory, String question, int step, Integer parentQuestionId, Date createdTimestamp, Set<QuestionResponse> questionResponses) {
       this.id = id;
       this.questionCategory = questionCategory;
       this.question = question;
       this.step = step;
       this.parentQuestionId = parentQuestionId;
       this.createdTimestamp = createdTimestamp;
       this.questionResponses = questionResponses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_fk", nullable=false)
    public QuestionCategory getQuestionCategory() {
        return this.questionCategory;
    }
    
    public void setQuestionCategory(QuestionCategory questionCategory) {
        this.questionCategory = questionCategory;
    }

    
    @Column(name="question", nullable=false)
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }

    
    @Column(name="step", nullable=false)
    public int getStep() {
        return this.step;
    }
    
    public void setStep(int step) {
        this.step = step;
    }

    
    @Column(name="parent_question_id")
    public Integer getParentQuestionId() {
        return this.parentQuestionId;
    }
    
    public void setParentQuestionId(Integer parentQuestionId) {
        this.parentQuestionId = parentQuestionId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_timestamp", nullable=false, length=35)
    public Date getCreatedTimestamp() {
        return this.createdTimestamp;
    }
    
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="questions")
    public Set<QuestionResponse> getQuestionResponses() {
        return this.questionResponses;
    }
    
    public void setQuestionResponses(Set<QuestionResponse> questionResponses) {
        this.questionResponses = questionResponses;
    }




}


