package org.bpm.model;
// Generated May 13, 2023, 9:40:18 AM by Hibernate Tools 5.4.30.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserRolesId generated by hbm2java
 */
@Embeddable
public class UserRolesId  implements java.io.Serializable {


     private long userId;
     private String roles;

    public UserRolesId() {
    }

	
    public UserRolesId(long userId) {
        this.userId = userId;
    }
    public UserRolesId(long userId, String roles) {
       this.userId = userId;
       this.roles = roles;
    }
   


    @Column(name="user_id", nullable=false)
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }


    @Column(name="roles")
    public String getRoles() {
        return this.roles;
    }
    
    public void setRoles(String roles) {
        this.roles = roles;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserRolesId) ) return false;
		 UserRolesId castOther = ( UserRolesId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && ( (this.getRoles()==castOther.getRoles()) || ( this.getRoles()!=null && castOther.getRoles()!=null && this.getRoles().equals(castOther.getRoles()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getUserId();
         result = 37 * result + ( getRoles() == null ? 0 : this.getRoles().hashCode() );
         return result;
   }   


}


